#!/usr/bin/env sh

filename=$1

if	[ -z "$filename" ]
then
	echo "Please enter a filename. The only arg is the filename"
	exit 0
fi

duration=`exiftool -Duration $1 | awk '{ print $3 }'`
bytes=`wc -c $1 | awk '{ print $1 }'`

echo -e "layout: sermon\ncategory: video\nduration: '${duration}' \nlength: ${bytes}\nvideo_url:" | xclip -selection c

echo -e "duration: '$duration'"
echo -e "length: $bytes"
echo -e "copied to clipboard"
